# Generated by Django 3.1.7 on 2021-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
