# Generated by Django 3.1.7 on 2021-04-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Catalog',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='catagory_id',
            new_name='catalog_id',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='catagory_name',
            new_name='catalog_name',
        ),
    ]
